### ISSUE TITLE
Errors: No module named resource_identify

### ISSUE THREAD

**Issue by jordipiqueres** [PublicaMundi/ckanext-vectorstorer#1]
I have installed correctly ckan with some extensions on a Ubuntu 12.04 64bit system. Then, I wanted to add vectorstorer extension but it is appearing an error that I don't have any idea how to solve:

[Fri Feb 06 08:34:08 2015] [error] Exception AttributeError: "'NoneType' object has no attribute 'clearing'" in <bound method PluginEnvironment.__del__ of  Services for Environment '<default>'
[Fri Feb 06 08:34:08 2015] [error] > ignored
[Fri Feb 06 08:34:08 2015] [error] Exception AttributeError: "'NoneType' object has no attribute 'clearing'" in <bound method PluginEnvironment.__del__ of  Services for Environment '<default>'
[Fri Feb 06 08:34:08 2015] [error] > ignored
[Fri Feb 06 08:34:08 2015] [error] Exception TypeError: "'NoneType' object is not callable" in <bound method LGEOS320.__del__ of <shapely.geos.LGEOS320 object at 0x7f17a7016f58>> ignored
[Fri Feb 06 08:34:08 2015] [error] Exception TypeError: "'NoneType' object is not callable" in <bound method LGEOS320.__del__ of <shapely.geos.LGEOS320 object at 0x7f17a7016f58>> ignored
Error opening file for reading: Permission denied
Error opening file for reading: Permission denied
[Fri Feb 06 08:34:11 2015] [error] 2015-02-06 08:34:11,447 WARNI [ckan.plugins.core] Plugin 'googleanalytics' is using deprecated interface IGenshiStreamFilter
[Fri Feb 06 08:34:11 2015] [error] 2015-02-06 08:34:11,564 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
[Fri Feb 06 08:34:11 2015] [error] 2015-02-06 08:34:11,567 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
[Fri Feb 06 08:34:12 2015] [error] 2015-02-06 08:34:12,258 INFO  [ckan.lib.base]  / render time 0.605 seconds
[Fri Feb 06 08:34:12 2015] [error] 2015-02-06 08:34:12,999 WARNI [ckan.plugins.core] Plugin 'googleanalytics' is using deprecated interface IGenshiStreamFilter
[Fri Feb 06 08:34:13 2015] [error] 2015-02-06 08:34:13,120 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
[Fri Feb 06 08:34:13 2015] [error] 2015-02-06 08:34:13,123 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
[Fri Feb 06 08:34:13 2015] [error] 2015-02-06 08:34:13,385 INFO  [ckan.lib.base]  /api/i18n/en render time 0.002 seconds
[Fri Feb 06 08:34:31 2015] [error] 2015-02-06 08:34:31,405 INFO  [ckan.lib.base]  / render time 0.628 seconds
[Fri Feb 06 08:34:31 2015] [error] 2015-02-06 08:34:31,499 INFO  [ckan.lib.base]  /api/i18n/en render time 0.002 seconds
[Fri Feb 06 08:34:37 2015] [error] Exception AttributeError: "'NoneType' object has no attribute 'clearing'" in <bound method PluginEnvironment.__del__ of  Services for Environment '<default>'
[Fri Feb 06 08:34:37 2015] [error] > ignored
[Fri Feb 06 08:34:37 2015] [error] Exception AttributeError: "'NoneType' object has no attribute 'clearing'" in <bound method PluginEnvironment.__del__ of  Services for Environment '<default>'
[Fri Feb 06 08:34:37 2015] [error] > ignored
[Fri Feb 06 08:34:37 2015] [error] Exception TypeError: "'NoneType' object is not callable" in <bound method LGEOS320.__del__ of <shapely.geos.LGEOS320 object at 0x7f179efcb050>> ignored
[Fri Feb 06 08:34:37 2015] [error] Exception TypeError: "'NoneType' object is not callable" in <bound method LGEOS320.__del__ of <shapely.geos.LGEOS320 object at 0x7f17a7020f58>> ignored
[Fri Feb 06 08:34:41 2015] [error] 2015-02-06 08:34:41,247 WARNI [ckan.plugins.core] Plugin 'googleanalytics' is using deprecated interface IGenshiStreamFilter
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205] mod_wsgi (pid=31654): Target WSGI script '/etc/ckan/default/apache.wsgi' cannot be loaded as Python module.
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205] mod_wsgi (pid=31654): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205] Traceback (most recent call last):
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]   File "/etc/ckan/default/apache.wsgi", line 10, in <module>
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]     application = loadapp('config:%s' % config_filepath)
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]     return loadobj(APP, uri, name=name, *_kw)
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]     return context.create()
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]     return self.object_type.invoke(self)
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]     return fix_call(context.object, context.global_conf, *_context.local_conf)
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/util.py", line 56, in fix_call
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]     val = callable(_args, *_kw)
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware.py", line 57, in make_app
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]     load_environment(conf, app_conf)
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 232, in load_environment
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]     p.load_all(config)
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 134, in load_all
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]     load(_plugins)
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 149, in load
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]     service = _get_service(plugin)
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 255, in _get_service
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]     return plugin.load()(name=plugin_name)
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1989, in load
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]     entry = __import__(self.module_name, globals(),globals(), ['**name**'])
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckanext-vectorstorer/ckanext/vectorstorer/plugin.py", line 7, in <module>
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]     from ckanext.vectorstorer import resource_actions
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckanext-vectorstorer/ckanext/vectorstorer/resource_actions.py", line 13, in <module>
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205]     from ckanext.publicamundi.model.resource_identify import ResourceIdentify
[Fri Feb 06 08:34:41 2015] [error] [client 10.0.26.205] ImportError: No module named resource_identify
[Fri Feb 06 08:34:41 2015] [error] 2015-02-06 08:34:41,993 WARNI [ckan.plugins.core] Plugin 'googleanalytics' is using deprecated interface IGenshiStreamFilter
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205] mod_wsgi (pid=31653): Target WSGI script '/etc/ckan/default/apache.wsgi' cannot be loaded as Python module.
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205] mod_wsgi (pid=31653): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205] Traceback (most recent call last):
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]   File "/etc/ckan/default/apache.wsgi", line 10, in <module>
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]     application = loadapp('config:%s' % config_filepath)
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]     return loadobj(APP, uri, name=name, *_kw)
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]     return context.create()
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]     return self.object_type.invoke(self)
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]     return fix_call(context.object, context.global_conf, *_context.local_conf)
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/util.py", line 56, in fix_call
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]     val = callable(_args, *_kw)
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware.py", line 57, in make_app
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]     load_environment(conf, app_conf)
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 232, in load_environment
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]     p.load_all(config)
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 134, in load_all
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]     load(_plugins)
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 149, in load
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]     service = _get_service(plugin)
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 255, in _get_service
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]     return plugin.load()(name=plugin_name)
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1989, in load
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]     entry = __import__(self.module_name, globals(),globals(), ['**name**'])
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckanext-vectorstorer/ckanext/vectorstorer/plugin.py", line 7, in <module>
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]     from ckanext.vectorstorer import resource_actions
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckanext-vectorstorer/ckanext/vectorstorer/resource_actions.py", line 13, in <module>
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205]     from ckanext.publicamundi.model.resource_identify import ResourceIdentify
[Fri Feb 06 08:34:42 2015] [error] [client 10.0.26.205] ImportError: No module named resource_identify

**Comment by drmalex07** [comment]
Hello @fibonaki. 

This extension is not meant to be used as a standalone CKAN extension (anymore). Instead, it's integrated as a plugin into `ckanext-publicamundi` extension (https://github.com/PublicaMundi/ckanext-publicamundi). Actually, the error you have encountered is a module dependency from this "parent" extension.

I suggest that you take a look at `ckanext-publicamundi`, where you can find some basic configuration examples to begin with.

**Comment by jordipiqueres** [comment]
Thank you for your response @drmalex07 ! :)

I did what you advised me but still I am having problems configuring "publicamundi_dataset publicamundi_vector publicamundi_raster" - I would like to have each one.

It is being a bit difficult to understand how dependencies or modules are linked each other. Indeed, It would be grateful to have more examples of configuration and a detailed documentation. I'm neither much familiarized with python, but I guess, as an extension of a product, wouldn't be difficult to be installed. 

By the way, I would appreciate any help for the following error: 

[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205] mod_wsgi (pid=4395): Target WSGI script '/etc/ckan/default/apache.wsgi' cannot be loaded as Python module.
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205] mod_wsgi (pid=4395): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205] Traceback (most recent call last):
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/etc/ckan/default/apache.wsgi", line 10, in <module>
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     application = loadapp('config:%s' % config_filepath)
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     return loadobj(APP, uri, name=name, *_kw)
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     return context.create()
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     return self.object_type.invoke(self)
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     return fix_call(context.object, context.global_conf, *_context.local_conf)
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/util.py", line 56, in fix_call
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     val = callable(_args, *_kw)
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware.py", line 57, in make_app
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     load_environment(conf, app_conf)
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 232, in load_environment
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     p.load_all(config)
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 134, in load_all
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     load(_plugins)
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 149, in load
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     service = _get_service(plugin)
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 255, in _get_service
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     return plugin.load()(name=plugin_name)
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1989, in load
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     entry = __import__(self.module_name, globals(),globals(), ['**name**'])
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext_publicamundi-1.2dev-py2.7.egg/ckanext/publicamundi/plugins.py", line 18, in <module>
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     import ckanext.publicamundi.lib.metadata as ext_metadata
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext_publicamundi-1.2dev-py2.7.egg/ckanext/publicamundi/lib/metadata/**init**.py", line 39, in <module>
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     from ckanext.publicamundi.lib.metadata.widgets import (
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext_publicamundi-1.2dev-py2.7.egg/ckanext/publicamundi/lib/metadata/widgets/**init**.py", line 229, in <module>
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     from ckanext.publicamundi.lib.metadata.widgets import objects as object_widgets
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext_publicamundi-1.2dev-py2.7.egg/ckanext/publicamundi/lib/metadata/widgets/objects/**init**.py", line 5, in <module>
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     from ckanext.publicamundi.lib.metadata.widgets.objects import _common
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext_publicamundi-1.2dev-py2.7.egg/ckanext/publicamundi/lib/metadata/widgets/objects/_common.py", line 8, in <module>
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     from ckanext.publicamundi.lib.metadata import schemata
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext_publicamundi-1.2dev-py2.7.egg/ckanext/publicamundi/lib/metadata/schemata/__init__.py", line 24, in <module>
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     from ckanext.publicamundi.lib.metadata.schemata._common import *
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext_publicamundi-1.2dev-py2.7.egg/ckanext/publicamundi/lib/metadata/schemata/_common.py", line 9, in <module>
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     from ckanext.publicamundi.lib.metadata import vocabularies
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext_publicamundi-1.2dev-py2.7.egg/ckanext/publicamundi/lib/metadata/vocabularies/__init__.py", line 48, in <module>
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     reference_data.get_path('inspire-vocabularies.json'),
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext_publicamundi-1.2dev-py2.7.egg/ckanext/publicamundi/reference_data/**init**.py", line 10, in get_path
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     raise ValueError('Path not found')
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205] ValueError: Path not found
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205] mod_wsgi (pid=4395): Target WSGI script '/etc/ckan/default/apache.wsgi' cannot be loaded as Python module.
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205] mod_wsgi (pid=4395): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205] Traceback (most recent call last):
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/etc/ckan/default/apache.wsgi", line 10, in <module>
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     application = loadapp('config:%s' % config_filepath)
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     return loadobj(APP, uri, name=name, *_kw)
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     return context.create()
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     return self.object_type.invoke(self)
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     return fix_call(context.object, context.global_conf, *_context.local_conf)
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/util.py", line 56, in fix_call
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     val = callable(_args, *_kw)
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware.py", line 57, in make_app
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     load_environment(conf, app_conf)
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 232, in load_environment
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     p.load_all(config)
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 134, in load_all
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     load(_plugins)
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 149, in load
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     service = _get_service(plugin)
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 255, in _get_service
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     return plugin.load()(name=plugin_name)
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1989, in load
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     entry = __import__(self.module_name, globals(),globals(), ['**name**'])
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext_publicamundi-1.2dev-py2.7.egg/ckanext/publicamundi/plugins.py", line 18, in <module>
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     import ckanext.publicamundi.lib.metadata as ext_metadata
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext_publicamundi-1.2dev-py2.7.egg/ckanext/publicamundi/lib/metadata/**init**.py", line 39, in <module>
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     from ckanext.publicamundi.lib.metadata.widgets import (
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext_publicamundi-1.2dev-py2.7.egg/ckanext/publicamundi/lib/metadata/widgets/**init**.py", line 227, in <module>
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205]     from ckanext.publicamundi.lib.metadata.widgets import base as base_widgets
[Mon Feb 09 10:09:25 2015] [error] [client 10.0.26.205] ImportError: cannot import name base

I don't know if this is the best way to ask for this problems.

Thank you in advance!

**Comment by drmalex07** [comment]
Hello @fibonaki 

Since setting-up `ckanext-publicamundi` involves several configuration steps that can be quite tricky and complex, i suggest that you start by deploying an instance driven by one of the ansible playbooks we provide. These deployment tools can be found at https://github.com/PublicaMundi/labs.geodata.gov.gr (see at deployment/common-debian for a debian-based deployment). If you follow this solution, you will end-up with a working CKAN instance that "wears" our custom "geodata" theme, but it's easy to restore the default theme by disabling `publicamundi_geodata_theme` plugin inside `development.ini`.   

Also, have in mind that `ckanext-publicamundi` is under heavy development and, for the moment, should not be considered as stable. We are preparing a major deployment at `geodata.gov.gr` (Greece's official portal for geo-related data) on a few months (May 2015), so expect a stable version to be delivered on approximatelly 2 months from now (April 2015).

One last thing: if you encounter problems (bugs, inconsistencies etc.) regarding `ckanext-publicamundi`i think you should post them directly to the issue list at https://github.com/PublicaMundi/ckanext-publicamundi/issues (because, as i said before, `ckanext-vectorstorer` is obsolete, and its functonality is integrated into `ckanext-publicamundi`).
